
CREATE DATABASE desafioBD; 

USE desafioBD;

CREATE TABLE Users(
    InternalID INT AUTO_INCREMENT UNIQUE NOT NULL,
    Nome VARCHAR(40) NOT NULL,
    AccessLevel VARCHAR(7) NOT NULL DEFAULT 'free',
    Senha VARCHAR(20),
    PhoneNumber VARCHAR(14) UNIQUE NOT NULL,
    ExternalID VARCHAR(24),
    LastUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(InternalID)
) ENGINE = INNODB;

CREATE TABLE Groups(
    GroupID INT AUTO_INCREMENT UNIQUE NOT NULL,
    Nome VARCHAR(20) NOT NULL,
    ExternalID VARCHAR(32),
    PRIMARY KEY(GroupID)
) ENGINE = INNODB;

CREATE TABLE UserGroup(
    UserID INT,
    GroupID INT,
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES Users(InternalID),
    CONSTRAINT FK_GroupID FOREIGN KEY (GroupID) REFERENCES Groups(GroupID),
    PRIMARY KEY (UserID, GroupID)
) ENGINE = INNODB;